### PR TITLE
Fix links :)

### PR DESCRIPTION
**Pull request by Shreyanand**
I wanted to try the examples but I found some links were not working so fixed them. Cheers!

### CODE REVIEW

**Comment by paulkass** [comment]
Hi @Shreyanand , thanks for the contribution. Would you mind signing the Salesforce CLA so we can accept your PR?

**Comment by Shreyanand** [comment]
> Hi @Shreyanand , thanks for the contribution. Would you mind signing the Salesforce CLA so we can accept your PR?

I did, it gave some error and asked me to contact support.

**Comment by georgettica** [comment]
If I'm already here, why not add some link checking?
(I would suggest adding a Cron to check the links aswell)

GitHub action example https://github.com/marketplace/actions/markdown-link-check

( Can be in a different PR, but still)

**Review by paulkass — APPROVED** [review]

**Comment by paulkass** [comment]
> If I'm already here, why not add some link checking?
> (I would suggest adding a Cron to check the links aswell)
> 
> GitHub action example https://github.com/marketplace/actions/markdown-link-check
> 
> ( Can be in a different PR, but still)

This is a good idea, I'm not sure why I haven't heard of this before.

**Pull request merged**
