### PR TITLE
Fix issue from AutoSARIMA

### PR DESCRIPTION
**Pull request by chenghaoliu89**
fix issue #26

### CODE REVIEW

**Comment by aadyotb** [comment]
This issue can arise in the following code snippet:
```python
# Load data
from ts_datasets.forecast import M4
from merlion.utils import TimeSeries
ts, md = M4("Hourly")[0]
train = TimeSeries.from_pd(ts[md.trainval])
test = TimeSeries.from_pd(ts[~md.trainval])

# Initialize model
from merlion.models.forecast.sarima import Sarima
from merlion.models.automl.autosarima import AutoSarima, AutoSarimaConfig
model = AutoSarima(model=Sarima(config=AutoSarimaConfig()))

# Model training will fail due to the above-mentioned error, since we don't have a SeasonalityDetection wrapper
model.train(train)
```
Would it be possible for you to maybe choose a default seasonality of 1 to address this issue?

**Comment by chenghaoliu89** [comment]
> This issue can arise in the following code snippet:
> 
> ```python
> # Load data
> from ts_datasets.forecast import M4
> from merlion.utils import TimeSeries
> ts, md = M4("Hourly")[0]
> train = TimeSeries.from_pd(ts[md.trainval])
> test = TimeSeries.from_pd(ts[~md.trainval])
> 
> # Initialize model
> from merlion.models.forecast.sarima import Sarima
> from merlion.models.automl.autosarima import AutoSarima, AutoSarimaConfig
> model = AutoSarima(model=Sarima(config=AutoSarimaConfig()))
> 
> # Model training will fail due to the above-mentioned error, since we don't have a SeasonalityDetection wrapper
> model.train(train)
> ```
> 
> Would it be possible for you to maybe choose a default seasonality of 1 to address this issue?

I see. The reason is the correct declaration for AutoSarima should be 
```
model = SeasonalityLayer(model=AutoSarima(model=Sarima(AutoSarimaConfig() )) )
```
The new implementation has separated seasonal detection from autosarima.

**Comment by chenghaoliu89** [comment]
> This issue can arise in the following code snippet:
> 
> ```python
> # Load data
> from ts_datasets.forecast import M4
> from merlion.utils import TimeSeries
> ts, md = M4("Hourly")[0]
> train = TimeSeries.from_pd(ts[md.trainval])
> test = TimeSeries.from_pd(ts[~md.trainval])
> 
> # Initialize model
> from merlion.models.forecast.sarima import Sarima
> from merlion.models.automl.autosarima import AutoSarima, AutoSarimaConfig
> model = AutoSarima(model=Sarima(config=AutoSarimaConfig()))
> 
> # Model training will fail due to the above-mentioned error, since we don't have a SeasonalityDetection wrapper
> model.train(train)
> ```
> 
> Would it make sense for you to maybe choose a default seasonality of 1 to address this issue? For example
> 
> ```python
> m = seasonal_order[-1]
> m = 1 if not isinstance(m, (int, float)) else m
> ```

I think the fundamental problem is the current API design does not match user's expectation. They prefer using `AutoSarima` instead of `SeasonalityLayer(model=AutoSarima())` at the first time.  In your case, I prefer to output some warning for correctly using seasonality detection module.

**Comment by aadyotb** [comment]
Let's go with that then. We can incorporate the seasonality detection module automatically once the AutoML module is more mature.

**Pull request merged**
